In [8]:
pip install nashpy

In [9]:
from google.colab import files 
  
  
uploaded = files.upload()

Saving Pankiv_lab5.csv to Pankiv_lab5 (3).csv


In [10]:
import nashpy as nash
import numpy as np
import pandas as pd
df = pd.read_csv('Pankiv_lab5 (3).csv')
df

b0  b1  b2  b3  b4
0   3   3  10   7   5
1   5   9   3   8   4
2   6   3  10   4   5
3   3   7  10   6   9
4   5   3   7   9  11

In [11]:
def minrow(row):
    return row.min()
desc = df.describe()
new_df = df.copy()
new_df['amin'] = new_df.apply(minrow, axis=1)
new_df.loc['bmax'] = desc.loc['max']
new_df

b0   b1    b2   b3    b4  amin
0     3.0  3.0  10.0  7.0   5.0   3.0
1     5.0  9.0   3.0  8.0   4.0   3.0
2     6.0  3.0  10.0  4.0   5.0   3.0
3     3.0  7.0  10.0  6.0   9.0   3.0
4     5.0  3.0   7.0  9.0  11.0   3.0
bmax  6.0  9.0  10.0  9.0  11.0   NaN

In [12]:
bmax = new_df.loc['bmax'].min()
amin = new_df['amin'].max()
bmaxid = new_df.loc['bmax'].idxmin()
aminid = new_df['amin'].idxmax()
print('Сідлова точка:',new_df[bmaxid][aminid])
print(f'Стовбець: {bmaxid}, Рядок: {aminid}')
if bmax != amin:
    print('Нижня ціна гри:',amin)
    print('Верхня ціна гри:',bmax)
    print(f'Гра не має вирішення в чистих стратегій: {bmax} != {amin}')

Сідлова точка: 3.0
Стовбець: b0, Рядок: 0
Нижня ціна гри: 3.0
Верхня ціна гри: 6.0
Гра не має вирішення в чистих стратегій: 6.0 != 3.0


In [14]:
# Знаходження домінуючих рядків
print('Знаходження домінуючих рядків:')
n = df.shape[0]
adellist = set()
for i in range(n): 
    for j in range(n):
        if i!=j and (df.loc[i]>=df.loc[j]).sum() == 5:
            print(f'{list(df.loc[i])} домінує над ,{list(df.loc[j])}')
            adellist.add(j)
# знаходження домінуючих стовпців
print('Знаходження домінуючих стовпців:')
n = df.shape[1]
bdellist = set()
for i in df.columns: 
    for j in df.columns:
        if i!=j and (df[i]<=df[j]).sum() == 5:
            print(f'{list(df[i])} домінує над ,{list(df[j])}')
            bdellist.add(j)
            
df.drop(adellist,inplace = True)
df.drop(bdellist,axis = 1,inplace = True)
df

Знаходження домінуючих рядків:
Знаходження домінуючих стовпців:


b0  b1  b2  b3  b4
0   3   3  10   7   5
1   5   9   3   8   4
2   6   3  10   4   5
3   3   7  10   6   9
4   5   3   7   9  11

In [15]:
df2 = df.copy()
desc2 = df2.describe()
df2['amin'] = df2.apply(minrow, axis=1)
df2.loc['bmax'] = desc2.loc['max']
df2

b0   b1    b2   b3    b4  amin
0     3.0  3.0  10.0  7.0   5.0   3.0
1     5.0  9.0   3.0  8.0   4.0   3.0
2     6.0  3.0  10.0  4.0   5.0   3.0
3     3.0  7.0  10.0  6.0   9.0   3.0
4     5.0  3.0   7.0  9.0  11.0   3.0
bmax  6.0  9.0  10.0  9.0  11.0   NaN

In [18]:
arr = pd.read_csv('Pankiv_lab5 (3).csv').to_numpy()
arr

array([[ 3,  3, 10,  7,  5],
       [ 5,  9,  3,  8,  4],
       [ 6,  3, 10,  4,  5],
       [ 3,  7, 10,  6,  9],
       [ 5,  3,  7,  9, 11]])

In [19]:
game = nash.Game(arr)
list2 = list(game.lemke_howson(initial_dropped_label=0))
print('Оптимальні змішані стратегії гравця А:')
print(list2[0])
print('Оптимальні змішані стратегії гравця B:')
print(list2[1])
print('Ціна гри:')
print(game[list2[0],list2[1]][0])

Оптимальні змішані стратегії гравця А:
[0.         0.40816327 0.44897959 0.         0.14285714]
Оптимальні змішані стратегії гравця B:
[0.73469388 0.14285714 0.         0.         0.12244898]
Ціна гри:
5.448979591836734


/usr/local/lib/python3.6/dist-packages/nashpy/integer_pivoting/integer_pivoting.py:31: RuntimeWarning: divide by zero encountered in true_divide
  return np.argmax(tableau[:, column_index] / tableau[:, -1])
